### ISSUE TITLE
你好， ruby中的笔记 买的是 阶段四全栈课程吗

### ISSUE THREAD

**Issue by johanazhu** [astak16/computer-basics#1]

**Comment by astak16** [comment]
rails 是的，ruby 不是

**Comment by astak16** [comment]
> _No description provided._

rails 是的，ruby 不是

**Comment by johanazhu** [comment]
> rails 是的，ruby 不是

哦哦，蛮好蛮好

**Comment by astak16** [comment]
> > rails 是的，ruby 不是
> 
> 哦哦，蛮好蛮好

你要学 ruby 吗，我当时看的是这个：https://www.bilibili.com/video/BV1RJ411Y7A4/?spm_id_from=333.999.0.0&vd_source=78aed90022f9db1abfe1d828237d3862

**Comment by johanazhu** [comment]
哦哦，我是看了方方的山竹记账，开始对 ruby 感兴趣，最近也在看书，也有看[重力不足](https://space.bilibili.com/25990460)的视频，你这个我还没看过，我看看，谢谢你的推荐

**Comment by astak16** [comment]
不客气，他里面还有一个视频 “ruby语言基础” ，比较简单，可以大致过一下语法（可看可不看）

**Comment by johanazhu** [comment]
> 不客气，他里面还有一个视频 “ruby语言基础” ，比较简单，可以大致过一下语法（可看可不看）

3Q
